[project]
name = "opensailor-collectstatic"
version = "0.1.0"
description = "Minimal dependencies for collectstatic only"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "django-htmx>=1.23.0",
    "django-storages[s3]>=1.14.2",
    "boto3>=1.34.69",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"