# Generated by Django 5.2.1 on 2025-05-09 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the boat designer",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "designer",
                "verbose_name_plural": "designers",
                "indexes": [
                    models.Index(fields=["name"], name="webapp_desi_name_6423ba_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the boat manufacturer",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "make",
                "verbose_name_plural": "makes",
                "indexes": [
                    models.Index(fields=["name"], name="webapp_make_name_a8e595_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the property", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this property represents"
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("float", "Float"),
                            ("options", "Options"),
                        ],
                        help_text="Type of input for this property",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="List of allowed options for OPTIONS type properties",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
                "indexes": [
                    models.Index(fields=["name"], name="webapp_prop_name_088577_idx"),
                    models.Index(
                        fields=["input_type"], name="webapp_prop_input_t_1892ea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sailboat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sailboat model", max_length=100
                    ),
                ),
                (
                    "manufactured_start_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year when production of this model started",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1800)],
                    ),
                ),
                (
                    "manufactured_end_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year when production of this model ended",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1800)],
                    ),
                ),
                (
                    "designers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Designers of the sailboat",
                        related_name="sailboats",
                        to="webapp.designer",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        help_text="Manufacturer of the sailboat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sailboats",
                        to="webapp.make",
                    ),
                ),
            ],
            options={
                "verbose_name": "sailboat",
                "verbose_name_plural": "sailboats",
            },
        ),
        migrations.CreateModel(
            name="SailboatProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "values",
                    models.JSONField(help_text="List of values for this property"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sailboat_values",
                        to="webapp.property",
                    ),
                ),
                (
                    "sailboat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_values",
                        to="webapp.sailboat",
                    ),
                ),
            ],
            options={
                "verbose_name": "sailboat property",
                "verbose_name_plural": "sailboat properties",
            },
        ),
        migrations.AddIndex(
            model_name="sailboat",
            index=models.Index(fields=["name"], name="webapp_sail_name_63aec1_idx"),
        ),
        migrations.AddIndex(
            model_name="sailboat",
            index=models.Index(
                fields=["manufactured_start_year"],
                name="webapp_sail_manufac_d776ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sailboat",
            index=models.Index(
                fields=["manufactured_end_year"], name="webapp_sail_manufac_54fc92_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sailboat",
            unique_together={("make", "name")},
        ),
        migrations.AddIndex(
            model_name="sailboatproperty",
            index=models.Index(
                fields=["sailboat", "property"], name="webapp_sail_sailboa_321a0c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sailboatproperty",
            unique_together={("sailboat", "property")},
        ),
    ]
