# Generated by Django 5.2.1 on 2025-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_attribute_input_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sailboat",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Photos of the sailboat",
                limit_choices_to={"media_type": "image"},
                related_name="sailboats",
                to="webapp.media",
            ),
        ),
    ]
