# Generated by Django 5.2.1 on 2025-05-15 00:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_media_sailboat_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sailboat",
            name="photos",
        ),
        migrations.CreateModel(
            name="SailboatImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.media"
                    ),
                ),
                (
                    "sailboat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.sailboat",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("sailboat", "order")},
            },
        ),
        migrations.AddField(
            model_name="sailboat",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Images of the sailboat",
                limit_choices_to={"media_type": "image"},
                related_name="sailboats",
                through="webapp.SailboatImage",
                to="webapp.media",
            ),
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hull_identification_number",
                    models.CharField(
                        help_text="Unique Hull Identification Number (HIN) for this vessel",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of this vessel", max_length=255),
                ),
                (
                    "year_built",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year this vessel was built",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1800)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sailboat",
                    models.ForeignKey(
                        help_text="The sailboat model this vessel is an instance of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessels",
                        to="webapp.sailboat",
                    ),
                ),
            ],
            options={
                "verbose_name": "vessel",
                "verbose_name_plural": "vessels",
            },
        ),
        migrations.CreateModel(
            name="VesselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.media"
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.vessel"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("vessel", "order")},
            },
        ),
        migrations.AddField(
            model_name="vessel",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Images of this specific vessel",
                limit_choices_to={"media_type": "image"},
                related_name="vessels",
                through="webapp.VesselImage",
                to="webapp.media",
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["hull_identification_number"],
                name="webapp_vess_hull_id_5f2f91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["year_built"], name="webapp_vess_year_bu_763e7a_idx"
            ),
        ),
    ]
