# Generated by Django 5.2.1 on 2025-05-15 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "webapp",
            "0006_remove_sailboat_photos_sailboatimage_sailboat_images_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SailboatGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SailboatUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="sailboat",
            options={
                "permissions": [
                    ("can_manage_sailboats", "Can manage sailboats"),
                    ("can_view_sailboats", "Can view sailboats"),
                ],
                "verbose_name": "sailboat",
                "verbose_name_plural": "sailboats",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_manage_sailboats", "Can manage sailboats"),
                    ("can_view_sailboats", "Can view sailboats"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="sailboat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sailboat",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this sailboat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sailboats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sailboat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="sailboat",
            index=models.Index(
                fields=["created_at"], name="webapp_sail_created_c8dfb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sailboat",
            index=models.Index(
                fields=["updated_at"], name="webapp_sail_updated_86e1f8_idx"
            ),
        ),
        migrations.AddField(
            model_name="sailboatgroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.sailboat"
            ),
        ),
        migrations.AddField(
            model_name="sailboatgroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="sailboatgroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="sailboatuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.sailboat"
            ),
        ),
        migrations.AddField(
            model_name="sailboatuserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="sailboatuserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sailboatgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
        migrations.AlterUniqueTogether(
            name="sailboatuserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
    ]
