# Generated by Django 5.2.1 on 2025-05-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_sailboatgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="home_port",
            field=models.CharField(
                blank=True,
                help_text="Home port of this vessel",
                max_length=255,
                null=True,
            ),
        ),
    ]
