# Generated by Django 5.2.1 on 2025-05-15 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_vessel_home_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The markdown content of the note"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created this note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        help_text="The vessel this note is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="webapp.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vessel note",
                "verbose_name_plural": "vessel notes",
                "indexes": [
                    models.Index(
                        fields=["vessel", "user"], name="webapp_vess_vessel__085bb8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="webapp_vess_created_9b7964_idx"
                    ),
                ],
                "unique_together": {("vessel", "user")},
            },
        ),
    ]
