# Generated by Django 5.2.1 on 2025-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_vesselnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="USCG_number",
            field=models.CharField(
                blank=True,
                help_text="Number issued by the USCG for this vessel",
                max_length=14,
                null=True,
                unique=True,
            ),
        ),
    ]
