# Generated by Django 5.2.1 on 2025-05-17 02:59

from django.db import migrations


def find_ethan(user_model):
    for possible_email in [
        "ethan.m.knox@gmail.com",
        "norton120@gmail.com",
        "ethan@knox.dev",
    ]:
        try:
            return user_model.objects.get(email=possible_email)
        except user_model.DoesNotExist:
            continue
    raise ValueError("Ethan not found")


def add_bootstrap_admin_user(apps, schema_editor):
    _ = schema_editor
    User = apps.get_model("webapp", "User")
    ethan = find_ethan(User)
    ethan.is_superuser = True
    ethan.is_staff = True
    ethan.role = "admin"
    ethan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_vessel_uscg_number"),
    ]

    operations = [
        migrations.RunPython(add_bootstrap_admin_user),
    ]
