# Generated by Django 5.2.1 on 2025-05-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_auto_20250517_0421"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="section",
            field=models.ForeignKey(
                default=1,
                help_text="Section this attribute belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="webapp.attributesection",
            ),
        ),
    ]
