# Generated by Django 5.2.1 on 2025-05-19 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_attribute_accepts_contributions_attribute_data_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vesselnote",
            name="content",
        ),
        migrations.AddField(
            model_name="vesselnote",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users this note is shared with",
                related_name="shared_vessel_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vesselnote",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this note",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_vessel_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="NoteMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The content of the note message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who wrote this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel_note",
                    models.ForeignKey(
                        help_text="The vessel note this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="webapp.vesselnote",
                    ),
                ),
            ],
            options={
                "verbose_name": "note message",
                "verbose_name_plural": "note messages",
                "ordering": ["created_at"],
            },
        ),
    ]
