# Generated by Django 5.2.1 on 2025-05-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_remove_vesselnote_content_vesselnote_shared_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="USCG_number",
            field=models.CharField(
                blank=True,
                help_text="Number issued by the USCG for this vessel",
                max_length=14,
                null=True,
            ),
        ),
    ]
