# Generated by Django 5.2.1 on 2025-08-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("webapp", "0017_alter_vessel_uscg_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("crew", "Crew"),
                            ("skipper", "Skipper"),
                        ],
                        default="viewer",
                        help_text="Role being requested",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from requester explaining why they need access",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=10,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this request was reviewed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "vessel access request",
                "verbose_name_plural": "vessel access requests",
            },
        ),
        migrations.CreateModel(
            name="VesselGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VesselUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_manage_sailboats", "Can manage sailboats"),
                    ("can_view_sailboats", "Can view sailboats"),
                    ("can_manage_vessels", "Can manage vessels"),
                    ("can_crew_vessels", "Can crew vessels"),
                    ("can_view_vessels", "Can view vessels"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelOptions(
            name="vessel",
            options={
                "permissions": [
                    ("can_manage_vessel", "Can manage vessel and assign roles"),
                    ("can_crew_vessel", "Can add logs and view detailed vessel info"),
                    ("can_view_vessel", "Can view private vessel details"),
                ],
                "verbose_name": "vessel",
                "verbose_name_plural": "vessels",
            },
        ),
        migrations.AddField(
            model_name="vessel",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created this vessel",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_vessels",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vessel",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether this vessel is publicly viewable or private",
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["is_public"], name="webapp_vess_is_publ_1046eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["created_by"], name="webapp_vess_created_d1d15f_idx"
            ),
        ),
        migrations.AddField(
            model_name="vesselaccessrequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User requesting access",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vessel_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vesselaccessrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_vessel_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vesselaccessrequest",
            name="vessel",
            field=models.ForeignKey(
                help_text="The vessel being requested access to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_requests",
                to="webapp.vessel",
            ),
        ),
        migrations.AddField(
            model_name="vesselgroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.vessel"
            ),
        ),
        migrations.AddField(
            model_name="vesselgroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="vesselgroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="vesseluserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.vessel"
            ),
        ),
        migrations.AddField(
            model_name="vesseluserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="vesseluserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="vesselaccessrequest",
            index=models.Index(
                fields=["vessel", "status"], name="webapp_vess_vessel__8bedaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselaccessrequest",
            index=models.Index(
                fields=["requester", "status"], name="webapp_vess_request_c1a31d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vesselaccessrequest",
            unique_together={("vessel", "requester")},
        ),
        migrations.AlterUniqueTogether(
            name="vesselgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
        migrations.AlterUniqueTogether(
            name="vesseluserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
    ]
