# Generated by Django 5.2.1 on 2025-08-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_vesselaccessrequest_vesselgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="hull_identification_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Hull Identification Number (HIN) for this vessel",
                max_length=14,
                null=True,
            ),
        ),
    ]
