name: Check OpenTofu Drift

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6:00 UTC

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/opensailor-github-actions-drift
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 'latest'

      - name: Initialize OpenTofu
        run: tofu init -input=false
        working-directory: opentofu

      - name: Check for drift
        id: plan
        run: |
          set -e
          tofu plan -detailed-exitcode -no-color
        working-directory: opentofu
        continue-on-error: true

      - name: Fail if drift detected
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Drift detected between OpenTofu IaC and AWS environment."
          exit 1