name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build docker images
      run: |
        docker compose build
    - name: Run tests with Docker Compose
      run: |
        set -a
        source .github/test.env
        set +a
        docker compose run --rm test